### ISSUE TITLE
菜单界面操作时，大概率出现电机重初始化现象

### ISSUE THREAD

**Issue by wenzhicode** [BETAFPV/LiteSilverware#1]
在菜单界面，上下选择选项时，不等时间内蓝灯闪烁，接着电机响两声，可以判断为电机重初始化。需要结合电调代码和飞控代码查。

**Comment by SchizoDuckie** [comment]
English Translation:
*Motor re-initialization occurs when the menu interface is operating. #1*
In the menu interface, when the option is selected up and down, the blue light flashes in unequal time, then the motor sounds twice, and it can be judged that the motor is re-initialized.  Need to combine the ESC code and the flight control code to check.

--

The original gesture operation function of the flight control code has not been deleted. After deletion, this problem no longer occurs.
