### ISSUE TITLE
Manual for Lite 1S Brushless FC.pdf Broken..

### ISSUE THREAD

**Issue by tobiasbischoff** [BETAFPV/LiteSilverware#10]
the PDF is broken and it seems the only source for this. Pretty hard to do anything...

**Comment by calef800** [comment]
This is the same for me

**Comment by wenzhicode** [comment]
The manual is in the docs folder. https://github.com/BETAFPV/LiteSilverware/blob/master/docs/Manual%20for%20Lite%201S%20Brushless%20FC.pdf

**Comment by tobiasbischoff** [comment]
Its BROKEN. Cannot open it.

**Comment by calef800** [comment]
The issue is definitely not fixed. I have obtained the newest manual from BETAFPV customer support. If you give me access to the repository I can add a new branch, put the file in, and make a pull request.
