### ISSUE TITLE
How to calibrate accelerometer

### ISSUE THREAD

**Issue by terrysahaidak** [BETAFPV/LiteSilverware#18]
I have betafpv 65s lite drone. I noticed a slight drift to the left and to the rear direction.

I would like to calibrate the accelerometer, and found this manual but it doesn't work for me:
https://betafpv.freshdesk.com/support/solutions/articles/27000045712-basic-user-manual-for-lite-fc-and-drone

Then I noticed this:
> Change parameters via OSD menu and original stick gestures are not supported.

Does this mean there is no way to run accelerometer calibration anymore?

**Comment by jumper047** [comment]
If it helps - accelerometer calibrates every startup.

**Comment by terrysahaidak** [comment]
It runs calibration if the aux 6 is on on each start up, am I right?

**Comment by jumper047** [comment]
Seems like it runs without conditions - 
https://github.com/BETAFPV/LiteSilverware/blob/master/Silverware/src/main.c#L466

**Comment by terrysahaidak** [comment]
I can see gyro calibration and then using previously saved accelerometer values. Did I miss something?

**Comment by jumper047** [comment]
Can you point me to that place in sources? As far as I see it is just the same function called via gestures..
BTW you can reenable gestures, but you'll need to recompile and flash your FC. Also I can try to add calibration to OSD menu, but you'll need an arduino and some soldering skills to update your osd

**Comment by terrysahaidak** [comment]
Sorry, I forgot to mention that betafpv 65s lite isn't running master, but specific branch according to its FC manual.

There is such commit https://github.com/BETAFPV/LiteSilverware/commit/c1c03f965c75bbbf2329bb0afda657041786144f

**Comment by jumper047** [comment]
f042_1s_bl is for 1s brushless board, not brushed one. As far as i know brushed code is in master.

**Comment by jumper047** [comment]
Actually it is in Brushedv2, but it is only two commits from master

**Comment by terrysahaidak** [comment]
Here is manual of that FC, check out FC firmware section.

But I think my current firmware is different because there is no turtle mode.

https://betafpv.freshdesk.com/support/solutions/articles/27000061074-manual-for-lite-brushed-fc-v2

I could be wrong though.

**Comment by jumper047** [comment]
Turtle mode is impossible with brushed motors - brushes will wear out in a moment. So I suppose this is some sort of mistake (may be copypaste from brushless manual)

**Comment by terrysahaidak** [comment]
is it possible to flash firmware via USB? I saw this as featurw-point on FC's page.

**Comment by jumper047** [comment]
Yes, ofcourse. First time you'll need shorten dfu pads to switch FC to dfu mode (newer versions enables dfu mode automatically when you plug usb cable). Process well described here - https://www.rcgroups.com/forums/showpost.php?p=44113693&postcount=21

**Comment by terrysahaidak** [comment]
Thanks for your help. I've got new radio which supports trimming, so I'll go with that for now.
