### ISSUE TITLE
Level_mode下悬停不稳，会不定方向飘移

### ISSUE THREAD

**Issue by wenzhicode** [BETAFPV/LiteSilverware#2]
在自稳模式下，需要打遥感才能悬停，不然会向某一个方向飘移。看下调节PID 或 查看飞控中误差计算部分。

**Comment by SchizoDuckie** [comment]
English Translation:
*Hovering under Level_mode is unstable and will drift indefinitely #2*
In the self-stabilizing mode, you need to use remote sensing to hover, or you will drift in a certain direction.  Look at the adjustment PID or see the error calculation section in the flight control.

**Comment by Rake1981** [comment]
I can confirm it , getting the same issue and same with the voltage sag .

**Comment by wenzhicode** [comment]
I asked a few people about the drift of the quadcopter and suspected it was caused by the accelerometer.However, I've been experimenting a lot lately, and there may be other factors as well,I changed some of the other parameters, and drift improves a little.

**Comment by terrysahaidak** [comment]
Hi @wenzhicode, how did you fix it? I have this problem with my BetaFPV 65s lite.

**Comment by wenzhicode** [comment]
See if the blades are not aligned，Or the joystick is not zero in the middle.

Try hovering in ACRO mode. If it is stable, then the accelerometer data is
wrong.

Terry Sahaidak <notifications@github.com> 于2020年11月4日周三 上午6:09写道：

**Comment by terrysahaidak** [comment]
Yeah, the acro mode works well. I've found gestures to call accelerometer calibration but couldn't get t working.
