### ISSUE TITLE
Release docs and source code for 1-2s firmware <- required by open source licence

### ISSUE THREAD

**Issue by DoctorMikeReddy** [BETAFPV/LiteSilverware#21]
Given silverware is open source, where is the update to include the 1-2s FC. On the “manual” page for installing Silverware firmware:
https://support.betafpv.com/hc/en-us/articles/900005303906-How-to-Flash-Firmware-of-Lite-FC
the 1-2s instructions are present, halfway down, but at the bottom of the page it says:
“ Lite 1-2S Brushless FC Firmware comming (sic) soon”

Neither is there a manual PDF for the 1-2s, which there is here:
https://github.com/BETAFPV/LiteSilverware/tree/master/docs
for the 1s and 2s versions.

At present, there is no way to see source code, or reinstall firmware if a problem arises. As this is an open source project, can this be remedied ASAP?

**Comment by wenzhicode** [comment]
Hi,DoctorMikeReddy 
If you want to modify the code, the source code can be provided to you.

**Comment by DoctorMikeReddy** [comment]
Yes please. Ideally, this should be via the beta FPV GitHub repo for Silverware.

**Comment by Diversionpfe** [comment]
Hi, I would like to have access as well to the source code now flashed in BetaFPV Lite Brushed Flight Controller V3, based on CPU MM32F103KBU6. Thank you in advance

**Comment by eccdev** [comment]
Hi, the same here regarding the V3 source code.
Thank You

**Comment by wenzhicode** [comment]
@eccdev  @Diversionpfe 
Hi, thanks for you using Lite Brushed Flight Controller V3 board.
LiteSilver V3 not open source code yet, I am very sorry fot this.
