### ISSUE TITLE
looptime of board V1 is unstable

### ISSUE THREAD

**Issue by wenzhicode** [BETAFPV/LiteSilverware#4]
飞控main函数中while循环一次的时间，如果过长，会导致进入control的时间过长，误差计算不准。

**Comment by SchizoDuckie** [comment]
English Translation:
*When the flight control while loop is too long, there will be jitter #4*

The time of the while loop in the main function of the flight control, if it is too long, will lead to too long time to enter the control, and the error calculation is not accurate.
