### ISSUE TITLE
电压低至某一值(6.5V左右)时，飞控电压快速下降，断电掉落重启。没有做低压报警。

### ISSUE THREAD

**Issue by wenzhicode** [BETAFPV/LiteSilverware#5]

**Comment by SchizoDuckie** [comment]
English translation:

*When the voltage is as low as a certain value (about 6.5V), the flight control voltage drops rapidly, and the power is turned off and restarted.  No low voltage alarms were made.  #5*

 The direct cause of the drop is the exhaustion of power.  The phenomenon is that the voltage is too low and the aircraft is dropped and restarted.  Continue to fly remotely, the voltage is quickly reduced to 5V-6V, and the battery is exhausted.
