### ISSUE TITLE
Airmode(brushless mix scaling) behavior onground

### ISSUE THREAD

**Issue by NotFastEnuf** [BETAFPV/LiteSilverware#8]
Please see https://github.com/NotFastEnuf/NFE_Silverware/commit/bb742176ccda449e6ece4aa4d64d8496fa8ed11b

Brushless mix scaling is intended to remain inactive while armed but still on the ground.  The first arming cycle after battery connect, the state variable to control brushless mix scaling is inactive as it should be.  However it has not been properly resetting after all following arm/disarm cycles.  Please apply this fix for better on ground behavior.

**Comment by wenzhicode** [comment]
Thanks , have added your patch.
