### ISSUE TITLE
Configuration for Betafpv Brushless 1s Silverware Frsky FC (pre-red edition)

### ISSUE THREAD

**Issue by ghostface** [BETAFPV/LiteSilverware#9]
Heya

What's the current settings needed to prepare a build for the betafpv brushless 1s silverware frysky fc. 
The black one (not the new red one altho I think configuration won't be any different) https://betafpv.com/collections/brushless-flight-controller/products/lite-1s-brushless-flight-controller

Is setting #define Lite_BrushlessRX in config.h enough?

Thank you and
BR Ghostface

**Comment by wenzhicode** [comment]
yes, you can use the branch f042_1s_bl directly or use the master branch,in master branch, just use #define f042_1s_bl in config.h
